---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

This is file creates the [DATA_SOURCE]IND.csv file using the [DATA_SOURCE].csv file.

## Read file
```{r}
library(dplyr)
setwd("C:/Users/wb533078/OneDrive - WBG/1 DATA UPDATE")
file = "C:/Users/wb533078/OneDrive - WBG/1 DATA UPDATE/Data/BEEPS/BEEPS.csv"
BEEPS = read.csv(file, sep = ",")
```

## Create IND file
```{r}
IND = BEEPS %>% select(dataset, question, answer)
IND = IND %>%mutate(ID.q = paste0(question, "-", answer))
IND = unique(IND)

colnames(IND)[1] = c("Dataset")
colnames(IND)[2] = c("Indicator_Name")
IND$Display_Name = IND$Indicator_Name
IND$Indicator_Id = ""
IND$Indicator = ""
IND$Rank = ""
IND$Category_11 = ""	
IND$Category_12 = ""	
IND$Category_13	= ""
IND$Category_14	= ""
IND$Category_15 = ""
IND$Category_21	= ""
IND$Category_22	= ""
IND$Category_23	= ""
IND$Category_24	= ""
IND$Category_25	= ""
IND$Category_31	= ""
IND$Category_32	= ""
IND$Category_33	= ""
IND$Category_34 = ""
IND$New1 = ""
IND$New2 = ""
IND$New3 = ""
IND$New4 = ""
IND$New5 = ""
IND$keyN = ""
```

```{r}
drops <- c("ID.q")
IND = IND[ , !(names(IND) %in% drops)]
write.csv(IND, file = "Data/BEEPS/BEEPSIND.csv", sep = ",", row.names = F)
```

```{r}
#Clean PEFA dataset - drop one unused column.
drops = c("encoded")
PEFA = PEFA[ , !(names(PEFA) %in% drops)] # Clean encoded column


PEFA = PEFA[is.na(PEFA$year) == F,] # Clean year NA rows
PEFA = PEFA[PEFA$year > 1969, ]

write.csv(PEFA, file = "Data/PEFA/PEFA.csv", sep = ",", row.names = F)
```

